### ISSUE TITLE
Restartボタンの配置

### ISSUE THREAD

**Issue by takayuki-fuwa** [Z-me/SOKUSEKI_Timer#3]
"Restart"ボタンの意味が正直分からない。
タイマーを"Stop"で停止した状態で"Start"ボタンをクリックしても何も起きないので、正直ビビる。
リセットボタンもあるので、「タイマー再開」処理も"Start"ボタンでやったほうがUI的に親切じゃないのかと。

**Comment by Z-me** [comment]
リッセットボタンを廃止し、START、STOP、RESETのみにしました。
スタートボタンを押せばまたリスタートします。

**Comment by takayuki-fuwa** [comment]
GJ!
